import type { Categorias, Lancamento } from "./types";

export const CATEGORIAS_INICIAIS: Categorias = {
  receitas: [
    "Venda de Equipamentos",
    "Instalação",
    "Manutenção Preventiva",
    "Manutenção Corretiva",
    "Contratos",
    "Outros Serviços",
  ],
  custos: [
    "Compra de Equipamentos",
    "Materiais",
    "Tubulações",
    "Gás Refrigerante",
    "Mão de Obra Técnica",
    "Terceirizações",
  ],
  despesas: [
    "Administrativo",
    "Marketing",
    "Combustível",
    "Veículos",
    "Aluguel",
    "Energia",
    "Internet",
    "Telefonia",
    "Sistemas",
    "Contabilidade",
    "Financeiro",
    "Outros",
  ],
  deducoes: ["Impostos", "Descontos", "Cancelamentos"],
  receitas_financeiras: ["Rendimento Aplicação", "Juros Recebidos"],
  despesas_financeiras: ["Juros Pagos", "Tarifas Bancárias", "IOF"],
};

const hoje = new Date();
const ym = (offset: number) => {
  const d = new Date(hoje.getFullYear(), hoje.getMonth() + offset, 10);
  return d.toISOString().slice(0, 10);
};

export const LANCAMENTOS_SEED: Lancamento[] = [
  {
    id: "seed-1",
    data: ym(0),
    tipo: "receita",
    categoria: "Venda de Equipamentos",
    descricao: "Venda Split 12.000 BTUs",
    contraparte: "Cliente João Silva",
    valor: 4500,
    status: "recebido",
  },
  {
    id: "seed-2",
    data: ym(0),
    tipo: "receita",
    categoria: "Instalação",
    descricao: "Instalação residencial",
    contraparte: "Cliente João Silva",
    valor: 800,
    status: "recebido",
  },
  {
    id: "seed-3",
    data: ym(0),
    tipo: "custo_direto",
    categoria: "Compra de Equipamentos",
    descricao: "Aquisição Split 12k",
    contraparte: "Fornecedor LG",
    valor: 2800,
    status: "pago",
  },
  {
    id: "seed-4",
    data: ym(0),
    tipo: "custo_direto",
    categoria: "Materiais",
    descricao: "Materiais elétricos",
    contraparte: "Casa do Eletricista",
    valor: 320,
    status: "pago",
  },
  {
    id: "seed-5",
    data: ym(0),
    tipo: "despesa_operacional",
    categoria: "Aluguel",
    descricao: "Aluguel do mês",
    contraparte: "Imobiliária Central",
    valor: 2200,
    status: "pago",
  },
  {
    id: "seed-6",
    data: ym(0),
    tipo: "despesa_operacional",
    categoria: "Combustível",
    descricao: "Gasolina veículos",
    contraparte: "Posto Shell",
    valor: 650,
    status: "pago",
  },
  {
    id: "seed-7",
    data: ym(-1),
    tipo: "receita",
    categoria: "Manutenção Preventiva",
    descricao: "PMOC mensal",
    contraparte: "Empresa Alpha",
    valor: 1800,
    status: "recebido",
  },
  {
    id: "seed-8",
    data: ym(-1),
    tipo: "receita",
    categoria: "Contratos",
    descricao: "Contrato manutenção",
    contraparte: "Condomínio Edifício Sol",
    valor: 3500,
    status: "recebido",
  },
  {
    id: "seed-9",
    data: ym(-1),
    tipo: "custo_direto",
    categoria: "Gás Refrigerante",
    descricao: "Recarga R-410A",
    contraparte: "Fornecedor Frio",
    valor: 480,
    status: "pago",
  },
  {
    id: "seed-10",
    data: ym(-1),
    tipo: "despesa_operacional",
    categoria: "Marketing",
    descricao: "Anúncios online",
    contraparte: "Google",
    valor: 400,
    status: "pago",
  },
  {
    id: "seed-11",
    data: ym(-2),
    tipo: "receita",
    categoria: "Manutenção Corretiva",
    descricao: "Reparo compressor",
    contraparte: "Cliente Maria",
    valor: 950,
    status: "recebido",
  },
  {
    id: "seed-12",
    data: ym(-2),
    tipo: "despesa_financeira",
    categoria: "Tarifas Bancárias",
    descricao: "Tarifas conta PJ",
    contraparte: "Banco do Brasil",
    valor: 89.9,
    status: "pago",
  },
];
